SELECT 
    TS.DESCRIPCION ||','|| S.DESCRIPCION AS SISTEMA_SALUD
    , COUNT(A.ATE_ID) AS ATENCION_DIARIA

FROM ATENCION A
    JOIN PACIENTE P ON A.PAC_RUN = P.PAC_RUN
    JOIN SALUD S ON P.SAL_ID = S.SAL_ID
    JOIN TIPO_SALUD TS ON TS.TIPO_SAL_ID = S.TIPO_SAL_ID

WHERE EXTRACT(YEAR FROM A.FECHA_ATENCION)=EXTRACT(YEAR FROM SYSDATE)
    AND EXTRACT(MONTH FROM A.FECHA_ATENCION)=9

GROUP BY    TS.DESCRIPCION 
                    , S.DESCRIPCION

HAVING COUNT(A.ATE_ID) >(
            SELECT
                    AVG(COUNT (A.ATE_ID)) AS ATE_DIA
            FROM ATENCION A
                    JOIN PACIENTE P        ON A.PAC_RUN = P.PAC_RUN
                    JOIN SALUD S             ON P.SAL_ID = S.SAL_ID
                    JOIN TIPO_SALUD TS  ON TS.TIPO_SAL_ID = S.TIPO_SAL_ID
            WHERE EXTRACT(YEAR FROM A.FECHA_ATENCION)=EXTRACT(YEAR FROM SYSDATE)
                    AND EXTRACT(MONTH FROM A.FECHA_ATENCION)=9
            GROUP BY TS.DESCRIPCION
                            , S.DESCRIPCION
                            )
           
                